### ISSUE TITLE
how can I find solution "uws_darwin_arm64_111.node"

### ISSUE THREAD

**Issue by alyos-coder** [httptoolkit/mockrtc#3] opened 2022-12-12 13:55 UTC
Error: Cannot find module './uws_darwin_arm64_111.node'
Falling back to a NodeJS implementation; performance may be degraded.

ReferenceError: mocha is not defined
    at Object.<anonymous> (/Users/alyos/firstproject/truffle-config.js:102:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Function.load (/Users/alyos/.nvm/versions/node/v19.2.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:152:1)
    at Function.detect (/Users/alyos/.nvm/versions/node/v19.2.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:141:1)
    at Object.module.exports [as run] (/Users/alyos/.nvm/versions/node/v19.2.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:12:1)
    at runCommand (/Users/alyos/.nvm/versions/node/v19.2.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:201:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by pimterry** [comment] 2022-12-12 17:59
@alyos-coder I don't think that's related to this library. I suspect uws is [uWebSockets](https://github.com/uNetworking/uWebSockets.js), a high-performance websockets library, which includes some native code, which seems to not be loading correctly here.

Notably UWS is used within Truffle, using their own fork of this, which includes that exact error message here:

https://github.com/trufflesuite/uws-js-unofficial/blob/f3e88c168deec031135170a411df6d8683ebcf4c/src/uws.js#L37

Since the stacktrace below also shows a `truffle-config.js` file, I'd bet that UWS within Truffle is where this message comes from.

I wouldn't worry about it though - unless you're worried about super high performance this sounds like it shouldn't be an issue.

It looks like `mocha is not defined` is your real problem. That is an error that will crash whatever process or tests you're trying to run. You're probably not importing or configuring Mocha correctly.

Either way, this isn't a MockRTC issue, so I'm going to close this. If you do run into issues caused by MockRTC specifically, feel free to open another issue with more details.

**Closed by pimterry** 2022-12-12 17:59 UTC
